### PR TITLE
Conf file isn't generated

### PR DESCRIPTION
**Pull request by lolotoobo**
`php artisan vendor:publish --provider="Eusonlito\LaravelMeta\MetaServiceProvider"`doesn't generate config file

### CODE REVIEW

**Comment by eusonlito** [comment]
Do you have already a `config/meta.php` file?

It's working fine:

```sh
$> php artisan vendor:publish --provider="Eusonlito\LaravelMeta\MetaServiceProvider"

Copied File [/vendor/eusonlito/laravel-meta/src/config/config.php] To [/config/meta.php]

Publishing complete.
```

Why a pull-request and not a simple issue?

**Comment by lolotoobo** [comment]
I created a pull request cause I fucked sorry...

No I don't have a config/meta.php. I just copy it from vendors directory

**Comment by eusonlito** [comment]
Are you using my package or @Torann fork?

**Comment by lolotoobo** [comment]
I'm using your package and I have discovered the problem :) 

With the autodiscover function of Laravel I don"t add provider and alias.... By adding them in config/app.php it works......

**Comment by eusonlito** [comment]
:+1:

**Pull request closed without merging**
