### PR TITLE
publish only files related to laravel-meta

### PR DESCRIPTION
**Pull request by hootlex**

### CODE REVIEW

**Comment by eusonlito** [comment]
Thanks, but Laravel doesn't "republish" previous files existing in config folder. Configuration files are only published one time.

**Comment by hootlex** [comment]
Publishing assets for some packages is optional. That means that by running `php artisan vendor:publish` you will publish the files for all installed packages which most of the times is not ideal.

**Comment by eusonlito** [comment]
Ok, Thanks!!

**Comment by hootlex** [comment]
You are welcome :)

**Pull request merged**
