### PR TITLE
Add alias in MetaServiceProvider for injection

### LINKED ISSUE #19: Dependency injection mixed with Facade usage
I'm facing a problem when I inject the `\Eusonlito\LaravelMeta\Meta` instance in my controller and then trying to get the tags in my view (with the Facade). 

Here's a basic example:

```php
Route::get('/', function (\Eusonlito\LaravelMeta\Meta $meta) {
    $meta->set('title', 'Hello world');

    dd(Meta::get('title'));
});
```

As I expect this bit of code to dump 'Hello world', it actually dumps 'null'. It seems that the instance returned by the Meta Facade is not the same as the one retrieved by the injection mecanism.

When looking at the `MetaServiceProvider`, I first thought it requires to define an alias like this:
```php
    /**
     * Register the service provider.
     *
     * @return void
     */
    public function register()
    {
        $this->app->singleton(Meta::class, function () {
            return new Meta(config('meta'));
        });

        $this->app->alias(Meta::class, 'meta');
    }

    /**
     * Get the services provided by the provider.
     *
     * @return array
     */
    public function provides()
    {
        return [Meta::class, 'meta'];
    }
```

But still not working. 

Anyone else facing this issue ?

### PR DESCRIPTION
**Pull request by alexjoffroy**
Fix #19

### CODE REVIEW

**Review by eusonlito — COMMENTED** [review]
Class name resolution via `::class` is only available from PHP 5.5 and this package must support PHP 5.4 :)

**Review by eusonlito — COMMENTED** [review]
I'm using PHPUnit `PSR-0` namespace because used version 4.8 is comptabile with all tested PHP versions. Check https://travis-ci.org/eusonlito/laravel-Meta to tests review.

**Comment by alexjoffroy** [comment]
Hi :)

Tests seems ok, even in 5.4, no ?
https://travis-ci.org/eusonlito/laravel-Meta/jobs/383735080

Anyway, when I submitted my PR, I have a fork from commit 51f0b44979d700035eba9c9cd318f33411ba014e, tests were failing with my php 7.x:

```bash
PHP Fatal error:  Class 'PHPUnit_Framework_TestCase' not found in .../laravel-Meta/tests/Tests.php on line 4

Fatal error: Class 'PHPUnit_Framework_TestCase' not found in .../laravel-Meta/tests/Tests.php on line 4
```

Now, when I try from the current master, I don't have this one anymore :) So, I guess I can remove the commit.

Concerning "Class name resolution via `Meta::class`", is `Eusonlito\LaravelMeta\Meta` will be OK instead for 5.4 ?

Just as a sidenote, since [5.4 (and 5.5) are not supported anymore](http://php.net/supported-versions.php), is it still relevant to have support for them on this package ?

**Comment by eusonlito** [comment]
Done, Thanks!

**Pull request closed without merging**
