### PR TITLE
Twitter changed format of image

### PR DESCRIPTION
**Pull request by AraneaDev**
Quick fix for changed image format of cards from twitter:image:src to just twitter:image

### CODE REVIEW

**Comment by eusonlito** [comment]
Hi! This package is using `twitter:image` :)

**Comment by AraneaDev** [comment]
It rendered `twitter.image.src` for me... which isn't valid when u check the Twitter specs. Image did not work until I made this change ?

**Comment by eusonlito** [comment]
I think that you are using the Torann fork instead my package :)

https://github.com/Torann/laravel-meta-tags

**Comment by AraneaDev** [comment]
OMG, you're right ... switched to yours now since it was the more active one .... dunno how I missed that!? Not enough coffee I guess ><

**Comment by eusonlito** [comment]
You are welcome! :smile:

**Pull request closed without merging**
